[package]
name = "rust_nanomsg"
version = "0.1.0"
authors = ["jonas <jonas.gastecker@sz-ybbs.ac.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanomsg = "0.7.2"
clipboard = "0.5.0"